export { default as TaskSolution1 } from './TaskSolution1/TaskSolution1'
export { default as TaskSolution2 } from './TaskSolution2/TaskSolution2'
export { default as TaskSolution3 } from './TaskSolution3/TaskSolution3'
export { default as TaskSolution4 } from './TaskSolution4/TaskSolution4'
export { default as TaskSolution5 } from './TaskSolution5/TaskSolution5'
